#!/bin/bash
# //====================================================
# //  System Request:Debian 9+/Ubuntu 18.04+/20+
# //  Author:  bhoikfostyahya
# //  Dscription: Xray Menu Management
# //  email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo -e "\e[42m       Add Shadowsocks Ws/Grpc Account   \E[0m"
  echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

  read -rp "User: " -e user
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\e[42m       Add Shadowsocks Ws/Grpc Account   \E[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo ""
    echo "A client with the specified name was already created, please choose another name."
    echo ""
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
  fi
done

cipher="aes-128-gcm"
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
read -p "Limit User (GB): " Quota
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#ssws$/a\###& '"$user $exp"'\
},{"password": "'""$uuid""'","method": "'""$cipher""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#ssgrpc$/a\###& '"$user $exp"'\
},{"password": "'""$uuid""'","method": "'""$cipher""'","email": "'""$user""'"' /etc/xray/config.json
echo $cipher:$uuid >/tmp/log
socks_base64=$(cat /tmp/log)
echo -n "${socks_base64}" | base64 >/tmp/log1
socks_base64e=$(cat /tmp/log1)
sockslink1="socks://$socks_base64@$domain:443?path=/socks5&security=tls&host=$domain&type=ws&sni=$domain#$user"
sockslink2="socks://$socks_base64@$domain:80?path=/socks5&security=none&host=$domain&type=ws#$user"
sockslink3="socks://$socks_base64@$domain:443?security=tls&encryption=none&type=grpc&serviceName=socks5-grpc&sni=$domain#$user"
systemctl restart xray
rm -rf /tmp/log
rm -rf /tmp/log1
cat >/var/www/html/socks-$user.txt <<-END
_______________________________________________________
           Thank You For Using Our Services
                Xray/Shdwsok Account
        Autoscript xray-lite dev Jengkolonline
_____________________script v.2_________________________
      System Request:Debian 9+/Ubuntu 18.04+/20+
      Author:  Jengkolonline
      Dscription: Xray Menu Management
      email: jengkolonline323@gmail.com
      telegram: https://t.me/Jengkol_Online
      installer script : 082372139631
_______________________________________________________
              Format Shadowsocks WS (CDN)
_______________________________________________________


{
"inbounds": [],
"outbounds": [
{
"mux": {
"enabled": true
},
"protocol": "socks",
"settings": {
"servers": [
{
"address": "$domain",
"port": 443,
"users": [
{
"level": 8,
"pass": "$pass",
"user": "$user"
}
]
}
]
},
"streamSettings": {
"network": "ws",
"security": "tls",
"tlsSettings": {
"allowInsecure": true,
"serverName": "$domain"
},
"wsSettings": {
"headers": {
"Host": "$domain"
},
"path": "/socks5"
}
},
"tag": "XRAY"
}
],
"policy": {
"levels": {
"8": {
"connIdle": 300,
"downlinkOnly": 1,
"handshake": 4,
"uplinkOnly": 1
}
}
}
}

_______________________________________________________
              Link Sockes5 Account
_______________________________________________________
Link TLS : ${sockslink1}
_______________________________________________________
Link NONE : ${sockslink2}
_______________________________________________________
Link gRPC : ${sockslink3}
_______________________________________________________

END

systemctl restart xray >/dev/null 2>&1
service cron restart >/dev/null 2>&1
if [ ! -e /etc/socks ]; then
  mkdir -p /etc/socks
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/socks/${user}
fi
DATADB=$(cat /etc/socks/.socks.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/socks/.socks.db
fi
echo "### ${user} ${exp} ${uuid}" >>/etc/shadowsocks/.shadowsocks.db
clear
echo -e "
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
\e[42mThank You For Using Our Services\E[0m
\e[42mShadowsocks WS/GRPC Account      \E[0m
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Remarks    : ${user}
Domain     : ${domain}
Location   : $CITY
User Quota : ${Quota} GB
Port TLS   : 443
Port NONE  : 80
Port  GRPC : 443
Password   : ${uuid}
Cipers     : aes-128-gcm
Network    : ws/grpc
Path       : /ss-ws
ServiceName: ss-grpc
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Link TLS   : ${sockslink1}
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Link NONE   : ${sockslink2}
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Link gRPC  : ${sockslink3}
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Link JSON  : http://${domain}:81/socks-$user.txt
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Expired On : $exp
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
" | tee -a /etc/log-create-user.log
read -n 1 -s -r -p "Press any key to back on menu"

menu

