#!/bin/bash
clear
# Getting
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Kulanbagong1/izinn/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Jengkol_Online"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6282372139631"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\033[42m"
UPDATE="https://raw.githubusercontent.com/Jengkolonline/XRAY/main/"
BOT="https://raw.githubusercontent.com/Jengkolonline/XRAY/main/"
Repo1="https://raw.githubusercontent.com/Kulanbagong1/izinn/main/"
ISP=$(cat /etc/xray/isp)
NS=$(cat /etc/xray/dns)
CITY=$(cat /etc/xray/city)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
Namee="Abdullah | JENGKOLONLINE | FREE TUNNEL"
DATEVPS=$(date +'%d/%m/%Y')
TIMEZONE=$(printf '%(%H:%M:%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)

#nginx=$( systemctl status nginx | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
#if [[ $nginx == "running" ]]; then
#    status_nginx="${GREEN}ON${NC}"
#else
#    status_nginx="${RED}OFF${NC}"
#fi

#xray=$( systemctl status xray | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
#if [[ $xray == "running" ]]; then
#    status_xray="${GREEN}ON${NC}"
#else
#    status_xray="${RED}OFF${NC}"
#fi

#haproxy=$( systemctl status haproxy | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
#if [[ $xray == "running" ]]; then
    status_haproxy="${GREEN}ON${NC}"
#else
    status_haproxy="${RED}OFF${NC}"
#fi

ttoday="$(vnstat | grep today | awk '{print $8" "substr ($9, 1, 3)}' | head -1)"
bmon="$(vnstat -m | grep `date +%G-%m` | awk '{print $8" "substr ($9, 1 ,3)}' | head -1)"

# // Exporting IP Address
export MYIP=$( curl -s https://ipinfo.io/ip/ )
Name=$(curl -sS ${Repo1}ip | grep $MYIP | awk '{print $2}')
Exp=$(curl -sS ${Repo1}ip | grep $MYIP | awk '{print $3}')

clear
echo -e "\033[31m┌───────────────────────────────────────────────┐\e[0m" 
echo -e " ${YELLOW}     _______  _________ ______  __ ${NC} ${RED}PREMIUM${NC}"
echo -e " ${YELLOW} __ / / __/ |/ / ___/ //_/ __ \/ / ${NC} ${RED}SCRIPT${NC}"
echo -e " ${YELLOW}/ // / _//    / (_ / ,< / /_/ / /__${NC} ${BLUE}========${NC}"
echo -e " ${YELLOW}\___/___/_/|_/\___/_/|_|\____/____/${NC}"
echo -e " ${RED}───────${NC} ${Green} / __ \/ |/ / /  /  _/ |/ / __//|  ${NC}"  
echo -e " ${RED}───────${NC} ${Green}/ /_/ /    / /___/ //    / _/> _< ${NC}"  
echo -e " ${RED}───────${NC} ${Green}\____/_/|_/____/___/_/|_/___/|/   ${NC}"
echo -e " ${Green}MULTI PROT PROT${FONT} (C)${GRAY} AUTO INSTALASI${NC}" 
echo -e "\033[31m└───────────────────────────────────────────────┘\e[0m"
#echo -e "  ${Blue}XRAY${NC}: [ ${status_xray} ]     ${Blue}NGINX${NC}: [ ${status_nginx} ${NC} ]   ${Blue}HAPROXY${NC}: [ ${status_haproxy} ${NC}]"
echo -e "\033[32m┌───────────────────────────────────────────────┐${NC}"
echo -e "\e[1;97m                     INFORMATION                \e[0m"
echo -e "\033[32m└───────────────────────────────────────────────┘${NC}"
echo -e ""
echo -e "   ${RED}System OS${NC}     :   ${putih}$MODEL${NC}"
echo -e "   ${RED}Server RAM${NC}    :   ${putih}$RAM MB $NC"
echo -e "   ${RED}Uptime Server${NC} :   ${putih}$SERONLINE${NC}"
echo -e "   ${RED}Core System${NC}   :   ${putih}$CORE${NC}"
echo -e "   ${RED}Date${NC}          :   ${putih}$DATEVPS${NC}"
echo -e "   ${RED}Time${NC}          :   ${putih}$TIMEZONE${NC}"
echo -e "   ${RED}Domain${NC}        :   ${putih}$domain${NC}"
echo -e "   ${RED}NS Domain${NC}     :   ${putih}$NS${NC}"
echo -e ""
echo -e "\033[32m┌───────────────────────────────────────────────┐${NC}"
echo -e "\e[1;97m                   CREATE ACCOUNT              \e[0m"
echo -e "\033[32m└───────────────────────────────────────────────┘${NC}"
echo -e ""
echo -e "   ${grenbo}[01] ${NC} ${putih}MENU SSH&OVPN ${NC}     |  ${grenbo}[06] ${NC} ${putih}MENU SHADOWSHOCK${NC}"
echo -e "   ${grenbo}[02] ${NC} ${putih}MENU VMESS${NC}         |  ${grenbo}[07] ${NC} ${putih}MENU SHADOWSHOCK2022${NC}"
echo -e "   ${grenbo}[03] ${NC} ${putih}MENU VLESS${NC}         |  ${grenbo}[08] ${NC} ${putih}MENU SETTING${NC}"
echo -e "   ${grenbo}[04] ${NC} ${putih}MENU TROJAN${NC}        |  ${grenbo}[09] ${NC} ${putih}ADD NOTIF BOT${NC}"
echo -e "   ${grenbo}[05] ${NC} ${putih}MENU SOKES 5${NC}       |  ${grenbo}[10] ${NC} ${putih}ADD BOT PANEL${NC}"
echo -e ""
echo -e "\033[32m┌───────────────────────────────────────────────┐${NC}"
echo -e "\e[1;97m                    NEWBIE TUNNEL              \e[0m"
echo -e "\033[32m└───────────────────────────────────────────────┘${NC}"
echo -e ""
echo -e "   ${RED}IP VPS${NC}        :  ${putih}$IPVPS${NC}"
echo -e "   ${RED}Client Name${NC}   :  ${putih}$Name${NC}"
echo -e "   ${RED}Exp Script${NC}    :  ${putih}$Exp${NC}"
echo -e "   ${RED}Name Author${NC}   :  ${putih}$Namee${NC}"
echo -e ""
echo -e "\033[32m└───────────────────────────────────────────────┘${NC}"
echo -e ""
read -p "   Select From Options [ 1 - 10 or x exit ] : " menu
case $menu in
1) clear ;
    ssh
    ;;
2) clear ;
    vmess
    ;;
3) clear ;
    vless
    ;;
4) clear ;
    trojan
    ;;
5) clear ;
    socksmenu
    ;;
6) clear ;
    shadowsocks
    ;;
7) clear ;
    socks22menu
    ;;
8) clear ;
    utility
    ;;
9) clear ;
   bot
   ;;
10) clear ;
  wget ${BOT}foldder/xolpanel.sh && chmod +x xolpanel.sh && ./xolpanel.sh
   ;;
x) clear ;
   exit
   ;;
*) clear ;
    menu
    ;;
esac
